In [2]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
import json
import csv

# Read JSON file (using raw string for safe path)
with open(r'D:\advanced_training_AIML\Advanced-Training-AIML-Python-\Day-9\file (1).json', 'r', encoding='utf-8') as json_file:
    data = json.load(json_file)

# Write to CSV
with open('output.csv', 'w', newline='', encoding='utf-8') as csv_file:
    writer = csv.DictWriter(csv_file, fieldnames=data[0].keys())
    writer.writeheader()
    writer.writerows(data)

print("✅ JSON converted to CSV successfully: output.csv")

✅ JSON converted to CSV successfully: output.csv

In [4]:
df = pd.read_csv(r'D:\advanced_training_AIML\Advanced-Training-AIML-Python-\Day-9\output.csv')

In [5]:
df.head()

,productId,productName,description,brand,category,price,currency,stock,images,variants,dimensions,ratings,reviews
0,1001,Wireless Headphones,Noise-cancelling wireless headphones with Blue...,SoundPro,Electronics,199.99,USD,"{'available': True, 'quantity': 50}","['https://example.com/products/1001/main.jpg',...","[{'variantId': '1001_01', 'color': 'Black', 'p...","{'weight': '0.5kg', 'width': '18cm', 'height':...","{'averageRating': 4.7, 'numberOfReviews': 120}","[{'reviewId': 501, 'userId': 101, 'username': ..."
1,1002,Smartphone Case,"Durable and shockproof case for smartphones, a...",CaseMate,Accessories,29.99,USD,"{'available': True, 'quantity': 200}","['https://example.com/products/1002/main.jpg',...","[{'variantId': '1002_01', 'color': 'Black', 'p...","{'weight': '0.2kg', 'width': '8cm', 'height': ...","{'averageRating': 4.4, 'numberOfReviews': 80}","[{'reviewId': 601, 'userId': 103, 'username': ..."
2,1003,4K Ultra HD Smart TV,55-inch 4K Ultra HD Smart TV with built-in Wi-...,Visionary,Electronics,799.99,USD,"{'available': True, 'quantity': 30}","['https://example.com/products/1003/main.jpg',...","[{'variantId': '1003_01', 'screenSize': '55 in...","{'weight': '15kg', 'width': '123cm', 'height':...","{'averageRating': 4.8, 'numberOfReviews': 250}","[{'reviewId': 701, 'userId': 105, 'username': ..."
3,1004,Bluetooth Speaker,Portable Bluetooth speaker with 12-hour batter...,AudioX,Electronics,59.99,USD,"{'available': True, 'quantity': 100}","['https://example.com/products/1004/main.jpg',...","[{'variantId': '1004_01', 'color': 'Red', 'pri...","{'weight': '0.3kg', 'width': '15cm', 'height':...","{'averageRating': 4.6, 'numberOfReviews': 150}","[{'reviewId': 801, 'userId': 107, 'username': ..."
4,1005,Winter Jacket,Men's water-resistant winter jacket with a fur...,ColdTech,Clothing,129.99,USD,"{'available': True, 'quantity': 80}","['https://example.com/products/1005/main.jpg',...","[{'variantId': '1005_01', 'size': 'M', 'color'...","{'weight': '1.5kg', 'width': '60cm', 'height':...","{'averageRating': 4.5, 'numberOfReviews': 60}","[{'reviewId': 901, 'userId': 109, 'username': ..."

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 13 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   productId    5 non-null      int64
 1   productName  5 non-null      object
 2   description  5 non-null      object
 3   brand        5 non-null      object
 4   category     5 non-null      object
 5   price        5 non-null      float64
 6   currency     5 non-null      object
 7   stock        5 non-null      object
 8   images       5 non-null      object
 9   variants     5 non-null      object
 10  dimensions   5 non-null      object
 11  ratings      5 non-null      object
 12  reviews      5 non-null      object
dtypes: float64(1), int64(1), object(11)
memory usage: 652.0+ bytes

In [7]:
df.describe()

         productId       price
count     5.000000    5.000000
mean   1003.000000  243.990000
std       1.581139  317.694822
min    1001.000000   29.990000
25%    1002.000000   59.990000
50%    1003.000000  129.990000
75%    1004.000000  199.990000
max    1005.000000  799.990000

In [8]:
df.columns

Index(['productId', 'productName', 'description', 'brand', 'category', 'price',
       'currency', 'stock', 'images', 'variants', 'dimensions', 'ratings',
       'reviews'],
      dtype='object')

In [14]:
df.head()

,productId,productName,description,brand,category,price,currency,stock,images,variants,dimensions,ratings,reviews
0,1001,Wireless Headphones,Noise-cancelling wireless headphones with Blue...,SoundPro,Electronics,199.99,USD,"{'available': True, 'quantity': 50}","['https://example.com/products/1001/main.jpg',...","[{'variantId': '1001_01', 'color': 'Black', 'p...","{'weight': '0.5kg', 'width': '18cm', 'height':...","{'averageRating': 4.7, 'numberOfReviews': 120}","[{'reviewId': 501, 'userId': 101, 'username': ..."
1,1002,Smartphone Case,"Durable and shockproof case for smartphones, a...",CaseMate,Accessories,29.99,USD,"{'available': True, 'quantity': 200}","['https://example.com/products/1002/main.jpg',...","[{'variantId': '1002_01', 'color': 'Black', 'p...","{'weight': '0.2kg', 'width': '8cm', 'height': ...","{'averageRating': 4.4, 'numberOfReviews': 80}","[{'reviewId': 601, 'userId': 103, 'username': ..."
2,1003,4K Ultra HD Smart TV,55-inch 4K Ultra HD Smart TV with built-in Wi-...,Visionary,Electronics,799.99,USD,"{'available': True, 'quantity': 30}","['https://example.com/products/1003/main.jpg',...","[{'variantId': '1003_01', 'screenSize': '55 in...","{'weight': '15kg', 'width': '123cm', 'height':...","{'averageRating': 4.8, 'numberOfReviews': 250}","[{'reviewId': 701, 'userId': 105, 'username': ..."
3,1004,Bluetooth Speaker,Portable Bluetooth speaker with 12-hour batter...,AudioX,Electronics,59.99,USD,"{'available': True, 'quantity': 100}","['https://example.com/products/1004/main.jpg',...","[{'variantId': '1004_01', 'color': 'Red', 'pri...","{'weight': '0.3kg', 'width': '15cm', 'height':...","{'averageRating': 4.6, 'numberOfReviews': 150}","[{'reviewId': 801, 'userId': 107, 'username': ..."
4,1005,Winter Jacket,Men's water-resistant winter jacket with a fur...,ColdTech,Clothing,129.99,USD,"{'available': True, 'quantity': 80}","['https://example.com/products/1005/main.jpg',...","[{'variantId': '1005_01', 'size': 'M', 'color'...","{'weight': '1.5kg', 'width': '60cm', 'height':...","{'averageRating': 4.5, 'numberOfReviews': 60}","[{'reviewId': 901, 'userId': 109, 'username': ..."

In [15]:
print(df.columns)
print(df.dtypes)

Index(['productId', 'productName', 'description', 'brand', 'category', 'price',
       'currency', 'stock', 'images', 'variants', 'dimensions', 'ratings',
       'reviews'],
      dtype='object')
productId        int64
productName     object
description     object
brand           object
category        object
price          float64
currency        object
stock           object
images          object
variants        object
dimensions      object
ratings         object
reviews         object
dtype: object

In [9]:
# Convert stringified dictionaries/lists back to Python objects safely
def safe_eval(x):
    try:
        return ast.literal_eval(x)
    except:
        return np.nan

nested_cols = ['stock', 'dimensions', 'ratings']
for col in nested_cols:
    df[col] = df[col].apply(safe_eval)

# Expand nested JSON-like columns
for col in nested_cols:
    expanded = pd.json_normalize(df[col])
    expanded.columns = [f"{col}.{sub}" for sub in expanded.columns]
    df = pd.concat([df, expanded], axis=1)

In [10]:
def clean_numeric(series):
    return pd.to_numeric(series.astype(str).str.replace(r'[^\d.]', '', regex=True),
                         errors='coerce')

num_cols = [
    'price', 'stock.quantity',
    'dimensions.weight', 'dimensions.width', 'dimensions.height', 'dimensions.depth',
    'ratings.averageRating', 'ratings.numberOfReviews'
]

for col in num_cols:
    if col in df.columns:
        df[col] = clean_numeric(df[col])

In [12]:
print("\n--- Dataset Overview ---")
print(df.describe(include='all').transpose())

# Count of products per category and brand
print("\nProducts by Category:\n", df['category'].value_counts())
print("\nProducts by Brand:\n", df['brand'].value_counts())

# Average price and rating by category
category_summary = df.groupby('category')[['price', 'ratings.averageRating']].mean().reset_index()
print("\nAverage Price & Rating by Category:\n", category_summary)

--- Dataset Overview ---
            count unique                                                top  \
productId     5.0    NaN                                                NaN
productName     5      5                                Wireless Headphones
description     5      5  Noise-cancelling wireless headphones with Blue...
brand           5      5                                           SoundPro
category        5      3                                        Electronics
price         5.0    NaN                                                NaN
currency        5      1                                                USD
stock         0.0    NaN                                                NaN
images          5      5  ['https://example.com/products/1001/main.jpg',...
variants        5      5  [{'variantId': '1001_01', 'color': 'Black', 'p...
dimensions    0.0    NaN                                                NaN
ratings       0.0    NaN                                                NaN
reviews         5      5  [{'reviewId': 501, 'userId': 101, 'username': ...

            freq    mean         std     min     25%     50%     75%     max
productId    NaN  1003.0    1.581139  1001.0  1002.0  1003.0  1004.0  1005.0
productName    1     NaN         NaN     NaN     NaN     NaN     NaN     NaN
description    1     NaN         NaN     NaN     NaN     NaN     NaN     NaN
brand          1     NaN         NaN     NaN     NaN     NaN     NaN     NaN
category       3     NaN         NaN     NaN     NaN     NaN     NaN     NaN
price        NaN  243.99  317.694822   29.99   59.99  129.99  199.99  799.99
currency       5     NaN         NaN     NaN     NaN     NaN     NaN     NaN
stock        NaN     NaN         NaN     NaN     NaN     NaN     NaN     NaN
images         1     NaN         NaN     NaN     NaN     NaN     NaN     NaN
variants       1     NaN         NaN     NaN     NaN     NaN     NaN     NaN
dimensions   NaN     NaN         NaN     NaN     NaN     NaN     NaN     NaN
ratings      NaN     NaN         NaN     NaN     NaN     NaN     NaN     NaN
reviews        1     NaN         NaN     NaN     NaN     NaN     NaN     NaN

Products by Category:
 category
Electronics    3
Accessories    1
Clothing       1
Name: count, dtype: int64

Products by Brand:
 brand
SoundPro     1
CaseMate     1
Visionary    1
AudioX       1
ColdTech     1
Name: count, dtype: int64

KeyError: "Columns not found: 'ratings.averageRating'"